# Site settings
title: Obesity
email: bhuiyan.zr@gmail.com
url: https://rahmanlaboratory.github.io/obesity/ #https://github.com/jeromelachaud/freelancer-theme
description: "Obesity, defined by BMI, is a global health concern linked to serious diseases. It's caused by more than just diet & exercise, with genes & social factors at play too. A combined approach of healthy habits, public health efforts, and accessible healthcare is needed to tackle this crisis."
keywords: "Obesity, Public Health, Global, Asia, Bangladesh"
skills: "Research > Findings > Implement"
meta_author: Bhuiyan ZiadRahman

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#- static : pass through formspree.io to validate email sending
#- disqus : replace contact form by disqus thread
#- comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ziad Rahman Bhuiyan
  location: Location
  social: Around the Web
  #credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Ziad_Bhuiyan
  - title: facebook
    url: https://www.facebook.com/profile.php?id=61557838765203
  - title: github
    url: https://ziad786.github.io/

  #- #title: #stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
  #- #title: #bitbucket
    #url: http://bitbucket.org/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Munshiganj
  - line: Dhaka, Bangladesh

# Credits content
credits: 'We are working to solve this issue.'


#'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
